### ISSUE TITLE
Mortgage ETL demo produce no output

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids-examples#15]
**Describe the bug**
GPU run’s ETL will produce 0 row

**Comment by GaryShen2008** [comment]
@nvliyuan Can we first update the parameters used in our examples to run GpuCSVScan to avoid this issue?

**Comment by nvliyuan** [comment]
Sure, will draft a pr.

**Comment by nvliyuan** [comment]
fix it by add configs #16
