### ISSUE TITLE
When reading perf/acq csv files, the reader should not use "option("header", true)"

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids-examples#166]
When reading perf/acq csv files, the reader should not use "option("header", true)".

https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.06/examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-ETL.ipynb is one example.

```
val reader = sparkSession.read.option("header", true).schema(performanceSchema)

val optionsMap = Map("header" -> "true")
```

The reason is the underline CSV files you downloaded does not have header.
If you do this, you end up reading one less row.

We need to set it false everywhere.

**Comment by nvliyuan** [comment]
fixed, closed
