### ISSUE TITLE
Example jars use inconsistent versioning

### ISSUE THREAD

**Issue by rwlee** [NVIDIA/spark-rapids-examples#217]
**Describe the bug**
Example jars use version numbers that are inconsistent with each other and do not reflect the branch or spark-rapids plugin version they are based on. This makes jars hard to track and makes written example code unpredictable/hard to use. 

branch-22.08 generates the following jars:
`yarn-gpu-mig-plugin-1.0.0.jar`
`rapids-4-spark-udf-examples_2.12-22.08.0-SNAPSHOT.jar`
`sample_xgboost_examples-0.2.3-SNAPSHOT-jar-with-dependencies.jar`
`spark-cuspatial-22.08.0-SNAPSHOT.jar`
`Spark-cuML/pca` example fails to build

**Steps/Code to reproduce bug**
`mvn package` various example directories in this repo.

**Expected behavior**
Versioning should match the branch number it is built off of.

**Comment by rwlee** [comment]
The XGBoost taxi jars also use `0.2.3` versioning number

**Comment by nvliyuan** [comment]
yes, it is a good idea to keep each demo version number consistent, will draft a pr to update

**Comment by nvliyuan** [comment]
close the issue for now since reconstructing the example repo, will reopen if still needed
