### ISSUE TITLE
Unable to Call Rapids UDF

### ISSUE THREAD

**Issue by mtsol** [NVIDIA/spark-rapids-examples#219]
Hi everyone, I am new to Rapids and might be my question will be dump to you, but I cannot find any example to call evaluateColumnar function of RapidsUDF interface from any spark statement, can any of you guide me?

**Comment by gerashegalov** [comment]
From the user perspective it's a regular UDF  `function` in Spark. Once registered it can be used in Spark SQL [expressions](2) on top of another input expression / column, for example, `function(a)`

RAPIDS Accelerator will call [evaluateColumnar](1) when the UDF is [marked with RapidsUDF](3) interface 

[1]: https://github.com/NVIDIA/spark-rapids/blob/8d6f6f5cc115e44d3b6afcdf85f4207f35912a69/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuUserDefinedFunction.scala#L59. 

[2]: https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.08/examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/python/rapids_udf_test.py#L44

[3]: https://github.com/NVIDIA/spark-rapids-examples/blob/f661b76b72a0caeae24bf9d69f5fd5524ee3f7ee/examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/scala/com/nvidia/spark/rapids/udf/scala/URLDecode.scala#L30

**Comment by mtsol** [comment]
@gerashegalov thanks for the response, can you tell, if I want to add some custom implementation which is not available in rapids, how an that be configured?

**Comment by gerashegalov** [comment]
Hi @mtsol, please take a look at [FAQ](https://nvidia.github.io/spark-rapids/docs/FAQ.html#how-can-i-run-custom-expressionsudfs-on-the-gpu) and the [UDF doc](https://nvidia.github.io/spark-rapids/docs/additional-functionality/rapids-udfs.html)

**Comment by mtsol** [comment]
My classes are:
package main.scala.sample

import ai.rapids.cudf.ColumnVector
import com.nvidia.spark.RapidsUDF

class MultiplyWithGPU extends Serializable with RapidsUDF {
  def apply(s: Seq[Any]): String = {
    (s(0).toString.toDouble * s(0).toString.toDouble).toString
  }
  override def evaluateColumnar(args: ColumnVector*): ColumnVector = {

    args.head.mul(args.head)

  }
}

And
package main.scala.sample

import org.apache.spark.SparkConf
import org.apache.spark.sql.functions.{col, struct, udf}
import org.apache.spark.sql.{Row, SparkSession}

object UDFTest{


  def randomStringGen(length: Int) = scala.util.Random.alphanumeric.take(length).mkString

  def randomNumGen(length: Int) = scala.util.Random.nextInt(length).toString

  def main(args: Array[String])={
    var dfSize = 1000
    var master = "local[*]"
    if (args.length > 0){
      dfSize = args(0).toInt
    }
    if (args.length > 1) {
      master = args(1)
    }

    val conf = new SparkConf()
      .setMaster(master)
      .setAppName("SomeApp")

    val spark = SparkSession
      .builder()
      .appName("basic example")
      .config(conf)
      .getOrCreate()

    val rdd = spark.sparkContext.parallelize(Seq.fill(dfSize) {
      (randomNumGen(10), randomStringGen(4), randomStringGen(6))
    }, 10)
    val df = spark.createDataFrame(rdd).toDF("a", "b", "c")
    df.show()
    val rapidMapper = spark.udf.register("df",{
      (r: Row) => (new MultiplyWithGPU())(r.toSeq)
    })

    val abc = df.withColumn("abc", rapidMapper(struct("a", "b")))
    abc.show(10)
  }
}


When i run my spark application with the following command, my application got stuck without showing any execution:
spark-submit --conf spark.rapids.sql.enabled=true --conf spark.executor.resource.gpu.amount=1 --conf spark.task.resource.gpu.amount=1 --conf spark.executor.resource.gpu.discoveryScript=./spark/examples/src/main/scripts/getGpusResources.sh --master=local --class main.scala.sample.UDFTest SparkGPUTesting.jar 100 local[*]


Can you help me out.

**Comment by GaryShen2008** [comment]
@firestarman Can you help here? Seems a simple use case.

**Comment by firestarman** [comment]
Hi @mtsol,

FIrst, to be a Scala UDF, you need to let your class extends from a `Function[T, R]`,
e.g. 
```
class MultiplyWithGPU extends Function[Int, Int] with RapidsUDF with Serializable
```
then try the following UDF registration.
```
    val rapidMapper = spark.udf.register("df",new MultiplyWithGPU())
```

**Comment by mtsol** [comment]
[logsSpark.txt](https://github.com/NVIDIA/spark-rapids-examples/files/9467673/logsSpark.txt)

**Comment by mtsol** [comment]
Hi, @gerashegalov , @firestarman , @GaryShen2008 can someone help me out with the issue, I have implemented the simple classes and run the application, it gets stuck while calculating DAG in spark. I am using a docker based environment for gpu based implementation. Here is a file to logs. [logsGPU.txt](https://github.com/NVIDIA/spark-rapids-examples/files/9468581/logsGPU.txt)

**Comment by firestarman** [comment]
@mtsol  Could you share your UDF jar? I can try it locally, or can you try the app with spark-shell instead of spark-submit ?

**Comment by firestarman** [comment]
One more thing, if you set master via `--master` in the command, maybe you do not need to set it again in your app main via the second parameter.

**Comment by mtsol** [comment]
[SparkGPUTesting.zip](https://github.com/NVIDIA/spark-rapids-examples/files/9489524/SparkGPUTesting.zip)

[code.zip](https://github.com/NVIDIA/spark-rapids-examples/files/9489535/code.zip)

@firestarman I am sharing the code and jar as well, can you run on your local and suggest any solution.

**Comment by firestarman** [comment]
I can run it successfully with the below command and code.
```
export RAPIDS_JAR=/jars/work/files/jars/rapids-4-spark_2.12-22.08.0-cuda11.jar
spark-shell \
    --conf spark.executor.cores=6  \
    --driver-memory 40G \
    --jars ${RAPIDS_JAR} \
    --conf spark.driver.extraJavaOptions=-Duser.timezone=UTC  \
    --conf spark.executor.extraJavaOptions=-Duser.timezone=UTC \
     --conf spark.sql.adaptive.enabled=false \
     --conf spark.rapids.sql.explain=ALL \
     --conf spark.plugins=com.nvidia.spark.SQLPlugin
```

```
import ai.rapids.cudf.ColumnVector
import com.nvidia.spark.RapidsUDF

class MultiplyWithGPU extends Function[Int, Int] with Serializable with RapidsUDF {
  def apply(s: Int): Int = s * s

  override def evaluateColumnar(args: ColumnVector*): ColumnVector = {
    args.head.mul(args.head)
  }
}


import org.apache.spark.SparkConf
import org.apache.spark.sql.functions.{col, struct, udf}
import org.apache.spark.sql.{Row, SparkSession}

def randomNumGen(length: Int) = scala.util.Random.nextInt(length)

val conf = new SparkConf().setAppName("SomeApp")
val spark = SparkSession.builder().appName("basic example").config(conf).getOrCreate()
val rdd = spark.sparkContext.parallelize(Seq.fill(1000) {
  (randomNumGen(10), randomNumGen(4), randomNumGen(6))
}, 10)
val df = spark.createDataFrame(rdd).toDF("a", "b", "c")
df.show()

val rapidMapper = spark.udf.register("df", new MultiplyWithGPU())
val abc = df.withColumn("abc", rapidMapper(col("a")))
abc.show(10)
```
Output:
```
+---+---+---+---+
|  a|  b|  c|abc|
+---+---+---+---+
|  3|  2|  1|  9|
|  6|  2|  0| 36|
|  9|  3|  1| 81|
|  1|  0|  3|  1|
|  5|  1|  5| 25|
|  7|  3|  0| 49|
|  6|  0|  2| 36|
|  9|  1|  0| 81|
|  1|  3|  3|  1|
|  2|  0|  1|  4|
+---+---+---+---+
only showing top 10 rows

```

**Comment by mtsol** [comment]
@firestarman @gerashegalov @GaryShen2008 do you guys have any dockerfile or image that can be used to execute spark jobs on gpus instead of setup the env on bare metal?

**Comment by mtsol** [comment]
scala> abc.show(10)
22/09/06 12:40:24 WARN GpuOverrides: 
!Exec <CollectLimitExec> cannot run on GPU because the Exec CollectLimitExec has been disabled, and is disabled by default because Collect Limit replacement can be slower on the GPU, if huge number of rows in a batch it could help by limiting the number of rows transferred from GPU to CPU. Set spark.rapids.sql.exec.CollectLimitExec to true if you wish to enable it
  @Partitioning <SinglePartition$> could run on GPU
  *Exec <ProjectExec> will run on GPU
    *Expression <Alias> cast(_1#4 as string) AS a#43 will run on GPU
      *Expression <Cast> cast(_1#4 as string) will run on GPU
    *Expression <Alias> cast(_2#5 as string) AS b#44 will run on GPU
      *Expression <Cast> cast(_2#5 as string) will run on GPU
    *Expression <Alias> cast(_3#6 as string) AS c#45 will run on GPU
      *Expression <Cast> cast(_3#6 as string) will run on GPU
    *Expression <Alias> cast(df(_1#4) as string) AS abc#46 will run on GPU
      *Expression <Cast> cast(df(_1#4) as string) will run on GPU
        *Expression <ScalaUDF> df(_1#4) will run on GPU
    ! <SerializeFromObjectExec> cannot run on GPU because not all expressions can be replaced; GPU does not currently support the operator class org.apache.spark.sql.execution.SerializeFromObjectExec
      @Expression <Alias> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._1 AS _1#4 could run on GPU
        ! <Invoke> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._1 cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.Invoke
          !Expression <KnownNotNull> knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) cannot run on GPU because input expression AssertNotNull assertnotnull(input[0, scala.Tuple3, true]) (ObjectType(class scala.Tuple3) is not supported); expression KnownNotNull knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) produces an unsupported type ObjectType(class scala.Tuple3)
            ! <AssertNotNull> assertnotnull(input[0, scala.Tuple3, true]) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.AssertNotNull
              ! <BoundReference> input[0, scala.Tuple3, true] cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.BoundReference
      @Expression <Alias> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._2 AS _2#5 could run on GPU
        ! <Invoke> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._2 cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.Invoke
          !Expression <KnownNotNull> knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) cannot run on GPU because input expression AssertNotNull assertnotnull(input[0, scala.Tuple3, true]) (ObjectType(class scala.Tuple3) is not supported); expression KnownNotNull knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) produces an unsupported type ObjectType(class scala.Tuple3)
            ! <AssertNotNull> assertnotnull(input[0, scala.Tuple3, true]) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.AssertNotNull
              ! <BoundReference> input[0, scala.Tuple3, true] cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.BoundReference
      @Expression <Alias> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._3 AS _3#6 could run on GPU
        ! <Invoke> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._3 cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.Invoke
          !Expression <KnownNotNull> knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) cannot run on GPU because input expression AssertNotNull assertnotnull(input[0, scala.Tuple3, true]) (ObjectType(class scala.Tuple3) is not supported); expression KnownNotNull knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) produces an unsupported type ObjectType(class scala.Tuple3)
            ! <AssertNotNull> assertnotnull(input[0, scala.Tuple3, true]) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.AssertNotNull
              ! <BoundReference> input[0, scala.Tuple3, true] cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.BoundReference
      ! <ExternalRDDScanExec> cannot run on GPU because not all expressions can be replaced; GPU does not currently support the operator class org.apache.spark.sql.execution.ExternalRDDScanExec
        !Expression <AttributeReference> obj#3 cannot run on GPU because expression AttributeReference obj#3 produces an unsupported type ObjectType(class scala.Tuple3)

========> multiply on GPU
+---+---+---+---+
|  a|  b|  c|abc|
+---+---+---+---+
|  8|  3|  4| 64|
|  2|  3|  5|  4|
|  9|  1|  3| 81|
|  6|  1|  0| 36|
|  4|  2|  0| 16|
|  3|  2|  1|  9|
|  9|  1|  2| 81|
|  3|  0|  1|  9|
|  1|  2|  4|  1|
|  1|  3|  3|  1|
+---+---+---+---+
only showing top 10 rows

**Comment by firestarman** [comment]
> @firestarman why I have such logs which says that the code cannot be run on GPU
> 
> ```
> scala> abc.show(10)
> 22/09/06 12:40:24 WARN GpuOverrides: 
> !Exec <CollectLimitExec> cannot run on GPU because the Exec CollectLimitExec has been disabled, and is disabled by default because Collect Limit replacement can be slower on the GPU, if huge number of rows in a batch it could help by limiting the number of rows transferred from GPU to CPU. Set spark.rapids.sql.exec.CollectLimitExec to true if you wish to enable it
>   @Partitioning <SinglePartition$> could run on GPU
>   *Exec <ProjectExec> will run on GPU
>     *Expression <Alias> cast(_1#4 as string) AS a#43 will run on GPU
>       *Expression <Cast> cast(_1#4 as string) will run on GPU
>     *Expression <Alias> cast(_2#5 as string) AS b#44 will run on GPU
>       *Expression <Cast> cast(_2#5 as string) will run on GPU
>     *Expression <Alias> cast(_3#6 as string) AS c#45 will run on GPU
>       *Expression <Cast> cast(_3#6 as string) will run on GPU
>     *Expression <Alias> cast(df(_1#4) as string) AS abc#46 will run on GPU
>       *Expression <Cast> cast(df(_1#4) as string) will run on GPU
>         *Expression <ScalaUDF> df(_1#4) will run on GPU
>     ! <SerializeFromObjectExec> cannot run on GPU because not all expressions can be replaced; GPU does not currently support the operator class org.apache.spark.sql.execution.SerializeFromObjectExec
>       @Expression <Alias> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._1 AS _1#4 could run on GPU
>         ! <Invoke> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._1 cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.Invoke
>           !Expression <KnownNotNull> knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) cannot run on GPU because input expression AssertNotNull assertnotnull(input[0, scala.Tuple3, true]) (ObjectType(class scala.Tuple3) is not supported); expression KnownNotNull knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) produces an unsupported type ObjectType(class scala.Tuple3)
>             ! <AssertNotNull> assertnotnull(input[0, scala.Tuple3, true]) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.AssertNotNull
>               ! <BoundReference> input[0, scala.Tuple3, true] cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.BoundReference
>       @Expression <Alias> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._2 AS _2#5 could run on GPU
>         ! <Invoke> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._2 cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.Invoke
>           !Expression <KnownNotNull> knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) cannot run on GPU because input expression AssertNotNull assertnotnull(input[0, scala.Tuple3, true]) (ObjectType(class scala.Tuple3) is not supported); expression KnownNotNull knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) produces an unsupported type ObjectType(class scala.Tuple3)
>             ! <AssertNotNull> assertnotnull(input[0, scala.Tuple3, true]) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.AssertNotNull
>               ! <BoundReference> input[0, scala.Tuple3, true] cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.BoundReference
>       @Expression <Alias> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._3 AS _3#6 could run on GPU
>         ! <Invoke> knownnotnull(assertnotnull(input[0, scala.Tuple3, true]))._3 cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.Invoke
>           !Expression <KnownNotNull> knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) cannot run on GPU because input expression AssertNotNull assertnotnull(input[0, scala.Tuple3, true]) (ObjectType(class scala.Tuple3) is not supported); expression KnownNotNull knownnotnull(assertnotnull(input[0, scala.Tuple3, true])) produces an unsupported type ObjectType(class scala.Tuple3)
>             ! <AssertNotNull> assertnotnull(input[0, scala.Tuple3, true]) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.objects.AssertNotNull
>               ! <BoundReference> input[0, scala.Tuple3, true] cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.BoundReference
>       ! <ExternalRDDScanExec> cannot run on GPU because not all expressions can be replaced; GPU does not currently support the operator class org.apache.spark.sql.execution.ExternalRDDScanExec
>         !Expression <AttributeReference> obj#3 cannot run on GPU because expression AttributeReference obj#3 produces an unsupported type ObjectType(class scala.Tuple3)
> 
> ========> multiply on GPU
> +---+---+---+---+
> |  a|  b|  c|abc|
> +---+---+---+---+
> |  8|  3|  4| 64|
> |  2|  3|  5|  4|
> |  9|  1|  3| 81|
> |  6|  1|  0| 36|
> |  4|  2|  0| 16|
> |  3|  2|  1|  9|
> |  9|  1|  2| 81|
> |  3|  0|  1|  9|
> |  1|  2|  4|  1|
> |  1|  3|  3|  1|
> +---+---+---+---+
> only showing top 10 rows
> ```

That's fine. We just need to make sure the ScalaUDF ran on GPU by the below line.
```
    *Expression <Alias> cast(df(_1#4) as string) AS abc#46 will run on GPU
      *Expression <Cast> cast(df(_1#4) as string) will run on GPU
        *Expression <ScalaUDF> df(_1#4) will run on GPU
```

**Comment by GaryShen2008** [comment]
Hi @mtsol, Though it's long time ago, are we good to close this issue?

**Comment by nvliyuan** [comment]
close since not valid, will open if nessesary
