### ISSUE TITLE
[Documentation] The Toree installation doc is out of date

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids-examples#22]
The document of [Apache Toree installation](https://github.com/NVIDIA/spark-rapids-examples/blob/branch-21.08/docs/get-started/xgboost-examples/notebook/toree.md#get-started-with-xgboost4j-spark-with-apache-toree-jupyter-notebook) is out of date, latest Toree v0.5.0-incubating-rc4 can be installed successfully.

**Comment by nvliyuan** [comment]
closed by #23
