### ISSUE TITLE
Add Custom Implementation to cudf ColumnVector class

### ISSUE THREAD

**Issue by mtsol** [NVIDIA/spark-rapids-examples#220]
I want to add my own implementation to ai.rapids.cudf.ColumnVector so that I can accelerate my custom tasks which are not supported by Rapids by default. Please, guide how I can do that.

**Comment by GaryShen2008** [comment]
Hi @mtsol, it seems you want to implement a native function to run on GPU.
Have you checked our examples https://github.com/NVIDIA/spark-rapids-examples/tree/branch-22.08/examples/UDF-Examples/RAPIDS-accelerated-UDFs? There're 2 samples of writing native code(cuda code).

The native code is in
https://github.com/NVIDIA/spark-rapids-examples/tree/branch-22.08/examples/UDF-Examples/RAPIDS-accelerated-UDFs/src/main/cpp/src.
The basic idea is that, you need to write a cuda code and provide the JNI APIs to call from the Java code, which can be ran in the JVM.

**Comment by GaryShen2008** [comment]
Close this issue since it's a question, but not an issue. And we have answered.
