### ISSUE TITLE
Data path checking logical problem of  XGBoost-PySpark agaricus examples 

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids-examples#255]
**Describe the bug**

https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.12/examples/XGBoost-Examples/agaricus/python/com/nvidia/spark/examples/agaricus/main.py#L61

```
if train_data is not None: --> if train_data is None:
```

https://github.com/NVIDIA/spark-rapids-examples/blob/branch-22.12/examples/XGBoost-Examples/agaricus/python/com/nvidia/spark/examples/agaricus/main.py#L61

```
if trans_data is not None: --> if trans_data is None:
```

**Comment by wbo4958** [comment]
Thx @NvTimLiu, do you know where can I  get the agaricus dataset?

**Comment by NvTimLiu** [comment]
> > Thx @NvTimLiu, do you know where can I get the agaricus dataset?
> 
> there is a sample dataset https://github.com/NVIDIA/spark-rapids-examples/tree/main/datasets

We also have XGBoost datasets on SwiftStack s3 bucket, which I already shared with Bobby offline.

**Comment by nvliyuan** [comment]
since #256 merged, closed this issue
