### ISSUE TITLE
Update RAPIDS accelerated UDF examples for static CUDA runtime

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-examples#344]
The RAPIDS Accelerator updated to a static CUDA runtime a while ago, but the RAPIDS accelerated UDF examples still use a dynamic CUDA runtime.  That means custom UDFs built based on the sample build environment in the examples may not run if the runtime environment does not provide the same CUDA runtime libraries that are available in the sample build environment.  The RAPIDS Accelerator would work (since it just needs the driver and nothing else) but the RAPIDS accelerated UDFs would not load properly due to the missing CUDA runtime libraries in the runtime env.

We should update the examples to show how to build properly with a static CUDA runtime for the custom UDF library so the custom UDFs will work in all environments that the RAPIDS Accelerator works.

**Comment by LIN-Yu-Ting** [comment]
Agree with this issue. Imagine that your native code jar is built in CUDA 11.8 environment and you try to run this in CUDA 12.0 environment then you might not be able to do that.

**Comment by GaryShen2008** [comment]
It seems simply to change the "CUDA_STATIC_RUNTIME ON" so that the udf.so won't link to cuda runtime dynamically. 
One question is that if we build in the docker with cuda11, but run with a spark-rapids plugin cuda12, will it be a problem?
If so, we should clarify in README to avoid such case.

**Comment by jlowe** [comment]
> It seems simply to change the "CUDA_STATIC_RUNTIME ON" 

Yes, I believe it's essentially that, although there's a couple of spots that need to be updated due to lack of variable reuse.  I'll post a PR shortly.

> if we build in the docker with cuda11, but run with a spark-rapids plugin cuda12, will it be a problem?

No.  Because we're statically linking the CUDA runtime, only the driver is required. The driver is backwards compatible with older CUDA runtimes.
