### ISSUE TITLE
Unable to execute spark SQL examples in a Spark Rapids environment

### ISSUE THREAD

**Issue by LIN-Yu-Ting** [NVIDIA/spark-rapids-examples#346]
**Describe the bug**

Unable to reproduce provided sample SQL in PySpark as following figure and error message.

![截圖 2024-01-16 上午10 29 13](https://github.com/NVIDIA/spark-rapids-examples/assets/62418760/4950e7d0-f3a2-4de1-8798-49b18d007c7b)

```
02:13:07.175 ERROR TaskSchedulerImpl - Lost executor 0 on 10.0.0.11: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
02:13:07.178 WARN  TaskSetManager - Lost task 0.0 in stage 2.0 (TID 2) (10.0.0.11 executor 0): ExecutorLostFailure (executor 0 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
02:13:29.229 ERROR TaskSchedulerImpl - Lost executor 1 on 10.0.0.11: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
02:13:29.229 WARN  TaskSetManager - Lost task 0.1 in stage 2.0 (TID 3) (10.0.0.11 executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
02:13:51.570 ERROR TaskSchedulerImpl - Lost executor 2 on 10.0.0.11: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
02:13:51.570 WARN  TaskSetManager - Lost task 0.2 in stage 2.0 (TID 4) (10.0.0.11 executor 2): ExecutorLostFailure (executor 2 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
02:14:14.405 ERROR TaskSchedulerImpl - Lost executor 3 on 10.0.0.11: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
02:14:14.405 WARN  TaskSetManager - Lost task 0.3 in stage 2.0 (TID 5) (10.0.0.11 executor 3): ExecutorLostFailure (executor 3 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
02:14:14.406 ERROR TaskSetManager - Task 0 in stage 2.0 failed 4 times; aborting job
```

**Steps/Code to reproduce bug**

I followed the tutorial to build rapids-4-spark-udf-examples_2.12-23.12.0-SNAPSHOT.jar and I am able to create it. After putting this jars under /home/spark-current/jars. Then I execute the sample SQL and I am not able to obtain the desired result. However, I am able to obtain result with another SQL query.

![截圖 2024-01-16 上午10 39 46](https://github.com/NVIDIA/spark-rapids-examples/assets/62418760/f34c90ec-d114-4480-8c2f-836e2a7b213b)

**Expected behavior**
I expect to get what tutorial expect to return.

**Environment details (please complete the following information)**
 - Environment location: [Standalone, Azure StandardNC4as_T4_v3]
 - Spark configuration settings related to the issue

```
spark.driver.cores 1
spark.driver.memory 6g
spark.driver.extraClassPath /home/spark-current/jars/rapids-4-spark_2.12-23.10.0-cuda12.jar
spark.executor.cores 4
spark.executor.memory 20g
spark.executor.resource.gpu.discoveryScript /tmp/getGpusResources.sh
spark.executor.resource.gpu.amount 1
spark.executor.extraClassPath /home/spark-current/jars/rapids-4-spark_2.12-23.10.0-cuda12.jar
spark.task.resource.gpu.amount 0.25
spark.task.cpus 1
spark.dynamicAllocation.enabled true
spark.shuffle.service.enabled true
spark.dynamicAllocation.minExecutors 1
spark.serializer org.apache.spark.serializer.KryoSerializer
spark.kryo.registrator com.nvidia.spark.rapids.GpuKryoRegistrator
spark.executor.extraJavaOptions -XX:+UseG1GC
spark.hadoop.io.compression.codecs org.seqdoop.hadoop_bam.util.BGZFEnhancedGzipCodec
spark.local.dir /mnt
spark.rapids.memory.pinnedPool.size 2g
spark.rapids.sql.concurrentGpuTasks 1
spark.rapids.sql.csv.read.double.enabled true
spark.rapids.sql.hasNans true
spark.rapids.sql.explain NOT_ON_GPU
spark.plugins com.nvidia.spark.SQLPlugin
```

**Comment by GaryShen2008** [comment]
Hi @LIN-Yu-Ting,

Thanks for reporting this issue.
Is it possible to check the executors' logs in your standalone cluster? The stderr or stdout log in the SPARK_HOME/work/<application-id>/<executor-id>/?

**Comment by LIN-Yu-Ting** [comment]
@GaryShen2008 This is the stderr of one of executor
```
root@7ae88f7da20c49e48c9ddbf89e51dbe6000000:/home/spark-current/work/app-20240116060142-0001# cat 0/stderr 
Spark Executor Command: "/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java" "-cp" "/home/spark-current/jars/rapids-4-spark_2.12-23.10.0-cuda12.jar:/home/spark-current/conf/:/home/spark-current/jars/*:/usr/local/hadoop-3.3.0/etc/hadoop/:/usr/local/hadoop-3.3.0/share/hadoop/common/lib/*:/usr/local/hadoop-3.3.0/share/hadoop/common/*:/usr/local/hadoop-3.3.0/share/hadoop/hdfs/:/usr/local/hadoop-3.3.0/share/hadoop/hdfs/lib/*:/usr/local/hadoop-3.3.0/share/hadoop/hdfs/*:/usr/local/hadoop-3.3.0/share/hadoop/yarn/:/usr/local/hadoop-3.3.0/share/hadoop/yarn/lib/*:/usr/local/hadoop-3.3.0/share/hadoop/yarn/*:/usr/local/hadoop-3.3.0/share/hadoop/mapreduce/lib/*:/usr/local/hadoop-3.3.0/share/hadoop/mapreduce/*:/contrib/capacity-scheduler/*.jar" "-Xmx20480M" "-Dspark.driver.port=34209" "-XX:+IgnoreUnrecognizedVMOptions" "--add-opens=java.base/java.lang=ALL-UNNAMED" "--add-opens=java.base/java.lang.invoke=ALL-UNNAMED" "--add-opens=java.base/java.lang.reflect=ALL-UNNAMED" "--add-opens=java.base/java.io=ALL-UNNAMED" "--add-opens=java.base/java.net=ALL-UNNAMED" "--add-opens=java.base/java.nio=ALL-UNNAMED" "--add-opens=java.base/java.util=ALL-UNNAMED" "--add-opens=java.base/java.util.concurrent=ALL-UNNAMED" "--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED" "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED" "--add-opens=java.base/sun.nio.cs=ALL-UNNAMED" "--add-opens=java.base/sun.security.action=ALL-UNNAMED" "--add-opens=java.base/sun.util.calendar=ALL-UNNAMED" "--add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED" "-XX:+UseG1GC" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@7ae88f7da20c49e48c9ddbf89e51dbe6000000.internal.cloudapp.net:34209" "--executor-id" "0" "--hostname" "10.0.0.11" "--cores" "4" "--app-id" "app-20240116060142-0001" "--worker-url" "spark://Worker@10.0.0.11:37895" "--resourcesFile" "/home/spark-current/work/app-20240116060142-0001/0/resource-executor-3543028932059117698.json"
========================================

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/mnt/spark-current/jars/atgenomix-plugin.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/mnt/spark-current/jars/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop-3.3.0/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java: symbol lookup error: /tmp/udfexamplesjni413332660788026425.so: undefined symbol: _ZN4cudf12copy_bitmaskERKNS_11column_viewEN3rmm16cuda_stream_viewEPNS3_2mr22device_memory_resourceE
```

I am not going to put stdout as it is long and without useful information.

**Comment by GaryShen2008** [comment]
Hi @LIN-Yu-Ting ,

From the stderr, "symbol lookup error: /tmp/udfexamplesjni413332660788026425.so: undefined symbol: _ZN4cudf12copy_bitmaskERKNS_11column_viewEN3rmm16cuda_stream_viewEPNS3_2mr22device_memory_resourceE", it failed to find the libcudf.so I think.

Did you use a single node to set up the spark standalone cluster or use multiple nodes?
If it's single node (driver and executors run on the same node), it's strange that one query succeeded but another failed.
If it's multiple nodes, I wonder if the rapids-4-spark_2.12-23.10.0-cuda12.jar wasn't copied to the executor's node so that it failed to find the library.

**Comment by GaryShen2008** [comment]
Or it may be the same problem as https://github.com/NVIDIA/spark-rapids-examples/issues/344.

**Comment by LIN-Yu-Ting** [comment]
> Hi @LIN-Yu-Ting ,
> 
> From the stderr, "symbol lookup error: /tmp/udfexamplesjni413332660788026425.so: undefined symbol: _ZN4cudf12copy_bitmaskERKNS_11column_viewEN3rmm16cuda_stream_viewEPNS3_2mr22device_memory_resourceE", it failed to find the libcudf.so I think.
> 
> Did you use a single node to set up the spark standalone cluster or use multiple nodes? If it's single node (driver and executors run on the same node), it's strange that one query succeeded but another failed. If it's multiple nodes, I wonder if the rapids-4-spark_2.12-23.10.0-cuda12.jar wasn't copied to the executor's node so that it failed to find the library.

@GaryShen2008 My spark environment is single node (driver and executors run on the same node)

**Comment by jlowe** [comment]
> From the stderr, "symbol lookup error: /tmp/udfexamplesjni413332660788026425.so: undefined symbol: _ZN4cudf12copy_bitmaskERKNS_11column_viewEN3rmm16cuda_stream_viewEPNS3_2mr22device_memory_resourceE", it failed to find the libcudf.so I think.

This might be a case of a mismatch between the libcudf.so used to build the examples and the one that was found at runtime.  The libcudf API is not backwards compatible from version to version, so it's important to build the UDF example against the same version of cudf that is being used at runtime by the RAPIDS Accelerator.

Note that the latest code on spark-rapids-examples main will build against libcudf from 23.12.0, but the version found at runtime appears to be 23.10.0.  I verified that the symbol in question is present in libcudf 23.12.0 but is missing from 23.10.0.

@LIN-Yu-Ting you will need to ensure the libcudf that is built against by the examples matches the version found at runtime, either by rolling the examples back to build against libcudf 23.10.0 or moving the RAPIDS Accelerator jar forward to version 23.12.0.

**Comment by GaryShen2008** [comment]
Please let me know if you solve the issue after using the same version of cudf like 23.12.0.

**Comment by LIN-Yu-Ting** [comment]
@GaryShen2008 @jlowe 
I recompiled rapids-4-spark-udf-examples_2.12-23.10.0-SNAPSHOT.jar with Spark Rapids 23.10.0 and run those erroneous commands and no more errors happen again.
