### ISSUE TITLE
[BUG] Java symbol lookup error in CICD run

### ISSUE THREAD

**Issue by cindyyuanjiang** [NVIDIA/spark-rapids-examples#377]
From STDOUT:
`/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java: symbol lookup error: /tmp/xxxxx.so: undefined symbol: xxxxx`

More details in CICD pipeline `examples-udf-examples-native`, run #139.

**Comment by GaryShen2008** [comment]
It seems a temporary issue, and not happen in recent running.

**Comment by nvliyuan** [comment]
close since should be pipeline issue
