### ISSUE TITLE
there is a dead link

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids-examples#402]
It seems the Agaricus dataset has been moved to another place.
```
ERROR: 1 dead links found!
[✖] https://gust.dev/r/xgboost-agaricus → Status: 404

FILE: ./docs/get-started/xgboost-examples/prepare-package-data/preparation-python.md
[✓] https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark_2.12/24.06.0/rapids-4-spark_2.12-24.06.0.jar → Status: 200
[/] /docs/get-started/xgboost-examples/building-sample-apps/python.md → Status: 0
[/] /docs/get-started/xgboost-examples/dataset/mortgage.md → Status: 0
[✓] https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page → Status: 200
[✖] https://gust.dev/r/xgboost-agaricus → Status: 404
```

**Comment by GaryShen2008** [comment]
Hi @wbo4958, can you help to find the dataset?

**Comment by wbo4958** [comment]
No idea the original dataset, but seems xgboost repo has agaricus, https://github.com/dmlc/xgboost/tree/master/demo/data ?

**Comment by parthosa** [comment]
Seeing more deadlinks in my PR #405

**Comment by parthosa** [comment]
Do we have an update on this? Existing PR seems to be blocked.

Here is a link I found for reference - https://web.archive.org/web/20200803173807/https://gust.dev/r/xgboost-agaricus

**Comment by nvliyuan** [comment]
Hi @parthosa , thx for the reference, please ignore the dead link issue, I will file a pr to fix it.

**Comment by GaryShen2008** [comment]
Fixed by PR 409. Close it.
