### ISSUE TITLE
Databricks notebooks should translate `dbfs:/` paths to `/dbfs/` formats automatically

### ISSUE THREAD

**Issue by parthosa** [NVIDIA/spark-rapids-examples#404]
Since the databricks notebooks only support event logs in the file API format (i.e. `/dbfs/`), we should automatically convert `dbfs:/` paths to `/dbfs/` for better user experience.

**Comment by tgravescs** [comment]
what databricks notebook and what is the context here?

**Comment by parthosa** [comment]
We have databricks notebooks for running qualification/profiling tool in this repo - [Link](https://github.com/NVIDIA/spark-rapids-examples/blob/d920adba0cd871b4d371c45d7e2b14ec6abb26aa/tools/databricks/%5BRAPIDS%20Accelerator%20for%20Apache%20Spark%5D%20Qualification%20Tool%20Notebook%20Template.ipynb)

Although mentioned in the notebook, some users might not be using `/dbfs/<path-to-eventlogs>` and instead pass the path as `dbfs:/<path-to-eventlogs>` (for example, copying the path from somewhere else). 

Hence this feature was requested so that the users can run the notebook even with `dbfs:/<path-to-eventlogs>`
