### ISSUE TITLE
A typo in ec2.md

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids-examples#65]
**Describe the bug**
A typo in ec2.md, 
https://github.com/NVIDIA/spark-rapids-examples/blob/branch-21.12/docs/get-started/xgboost-examples/csp/aws/ec2.md#step-41-edit-spark-defualtconf

defualtconf => defaultconf

**Comment by nvliyuan** [comment]
closed since #73 merged
