### ISSUE TITLE
Random data generation in PCA test case will cause OOM

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids-examples#89]
**Describe the bug**
`java.lang.OutOfMemoryError: Java heap space` is observed when generating random data for PCA test. Currently the data is generate at driver side. We should make this generation more rubust, like using RDD to generate mentioned here: https://stackoverflow.com/questions/55083170/efficient-way-to-generate-large-randomized-data-in-spark

**Comment by nvliyuan** [comment]
close since not valid
